source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "Omniscope-iOS" do
	pod 'CTAssetsPickerController'
	pod 'FBSDKShareKit'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'MHVideoPhotoGallery'
    pod 'CircleProgressBar'
    pod 'NYTPhotoViewer'
end
