source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "Omniscope-iOS" do
	pod 'CTAssetsPickerController'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'CircleProgressBar'
    pod 'ASVideoPlayer'
end
